package go_kcp

const (
	IKCP_LOG_OUTPUT    = 1
	IKCP_LOG_INPUT     = 2
	IKCP_LOG_SEND      = 4
	IKCP_LOG_RECV      = 8
	IKCP_LOG_IN_DATA   = 16
	IKCP_LOG_IN_ACK    = 32
	IKCP_LOG_IN_PROBE  = 64
	IKCP_LOG_IN_WINS   = 128
	IKCP_LOG_OUT_DATA  = 256
	IKCP_LOG_OUT_ACK   = 512
	IKCP_LOG_OUT_PROBE = 1024
	IKCP_LOG_OUT_WINS  = 2048
)
